# -*- coding: utf-8 -*-
"""Keylogger Detector (Anti-Keylogger Tool).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eb4Q6icWFg22wMjlhTuNt6SI1WJ_LnFo
"""

import psutil

# Simulated suspicious keywords for keyloggers
suspicious_keywords = ['keylogger', 'logkeys', 'keyboard', 'hook', 'capture']

def detect_suspicious_processes():
    found_suspicious = False
    print("Scanning running processes...\n")
    for proc in psutil.process_iter(['pid', 'name']):
        try:
            pname = proc.info['name'].lower()
            for keyword in suspicious_keywords:
                if keyword in pname:
                    print(f"⚠️ Suspicious process detected: {pname} (PID: {proc.info['pid']})")
                    found_suspicious = True
        except (psutil.NoSuchProcess, psutil.AccessDenied):
            continue

    if not found_suspicious:
        print("✅ No suspicious processes found. System appears clean.")

# Run scanner
detect_suspicious_processes()